create table orders (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    member_name varchar(255) not null,
    status varchar(50) not null,
    total_amount numeric(10, 2) not null,
    payment_method varchar(50),
    payment_id bigint,
    transaction_id varchar(255),
    created_at timestamp,
    updated_at timestamp
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    product_name varchar(255) not null,
    unit_price numeric(10, 2) not null,
    quantity integer not null,
    subtotal numeric(10, 2) not null,
    constraint fk_order_items_order_id
        foreign key (order_id) references orders (id) on delete cascade
);

create index idx_member_id on orders (member_id);
create index idx_status on orders (status);
create index idx_created_at on orders (created_at);
create index idx_order_items_order_id on order_items (order_id);
